export const GET_MESSAGE = 'GET_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const CONNECT = 'CONNECT';
export const DISCONNECT = 'DISCONNECT';
